cghub/apps/cart/urls.py
from django.conf.urls import patterns, url
from cghub.apps.cart.views import (
                CartAddItem, CartAddRemoveItemsView, CartClearView,
                CartDownloadFilesView, CartView)


urlpatterns = patterns('',
    url(
        r'^(?P<action>add|remove)/$',
        CartAddRemoveItemsView.as_view(), name='cart_add_remove_items'),
    url(
        r'^add/(?P<analysis_id>'
        '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        CartAddItem.as_view(), name='cart_add_item'),
    url(
        r'^clear/$',
        CartClearView.as_view(), name='cart_clear'),
    url(
        r'^(?P<action>manifest|metadata|summary|urls)/$',
        CartDownloadFilesView.as_view(), name='cart_download_files'),
    url(r'^$', CartView.as_view(), name='cart_page'),
)

cghub/apps/help/urls.py
from django.conf.urls import patterns, url

from cghub.apps.help.views import HelpView, HelpHintView, HelpTextView

urlpatterns = patterns(
    '',
    url(r'^$', HelpView.as_view(), name='help_page'),
    url(r'^overview/$',
        HelpView.as_view(template_name='help/overview.html'),
        name='help_overview_page'),
    url(r'^flow/$',
        HelpView.as_view(template_name='help/flow.html'),
        name='help_flow_page'),
    url(r'^batch/$',
        HelpView.as_view(template_name='help/batch.html'),
        name='help_batch_search_page'),
    url(r'^assemblies/$',
        HelpView.as_view(template_name='help/assemblies.html'),
        name='help_assemblies_page'),
    url(r'^hint/$', HelpHintView.as_view(), name='help_hint'),
    url(r'^text/$', HelpTextView.as_view(), name='help_text'),
)

cghub/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from cghub.apps.core.views import (
            HomeView, SearchView, BatchSearchView,
            ItemDetailsView, MetadataView, MessageView)


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name='home_page'),
    url(r'^search/$', SearchView.as_view(), name='search_page'),
    url(r'^search/batch/$', BatchSearchView.as_view(), name='batch_search_page'),
    url(r'^details/(?P<analysis_id>'
        '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        ItemDetailsView.as_view(), name='item_details'),
    url(r'^metadata/(?P<analysis_id>'
        '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        MetadataView.as_view(), name='metadata'),
    url(r'^message/(?P<message_id>\d+)/remove/$',
        MessageView.as_view(), name='message_remove'),
    url(r'^logout/', 'django.contrib.auth.views.logout',
        {'next_page': '/'}, name='logout'),
    url(r'^cart/', include('cghub.apps.cart.urls')),
    url(r'^help/', include('cghub.apps.help.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('django.views.generic.simple',
    url(
        r'^accessibility/$', 'direct_to_template',
        {'template': 'help/accessibility.html'}, name='accessibility_page'),
)

urlpatterns += staticfiles_urlpatterns()

handler500 = 'cghub.apps.core.views.error_500'
handler404 = 'cghub.apps.core.views.error_404'

cghub/apps/core/forms.py
import re

from django import forms
from django.conf import settings


class BatchSearchForm(forms.Form):

    text = forms.CharField(
                    required=False, widget=forms.Textarea,
                    label='Space separated ids')
    upload = forms.FileField(required=False, label='Or select file')

    def clean(self):
        data = self.cleaned_data
        upload = data.get('upload')
        text = data.get('text')

        if not upload and (not text or text.isspace()):
            raise forms.ValidationError('All fields are empty')

        # get list of ids
        raw_ids = []
        ids = []
        unvalidated_ids = []
        id_pattern = re.compile(settings.ID_PATTERN)
        legacy_sample_id_pattern = re.compile('^[a-z]{2,8}-[0-9a-z\-]{10,30}$')
        for i in text.split():
            id = i.strip()
            if not id:
                continue
            if id not in raw_ids:
                raw_ids.append(id)

        if upload:
            for i in upload.read().split():
                id = i.strip()
                if not id:
                    continue
                if id not in raw_ids:
                    raw_ids.append(id)

        for id in raw_ids:
            # only legacy sample id has all letters uppercased
            lower_id = id.lower()
            if id_pattern.match(lower_id):
                if lower_id not in ids:
                    ids.append(lower_id)
                continue
            elif legacy_sample_id_pattern.match(lower_id):
                if lower_id not in ids and lower_id.upper() not in ids:
                    ids.append(lower_id.upper())
                continue
            elif id not in unvalidated_ids:
                unvalidated_ids.append(id)

        if not ids:
            raise forms.ValidationError('No valid ids were found')

        data['raw_ids'] = raw_ids
        data['ids'] = ids
        data['unvalidated_ids'] = unvalidated_ids

        return data


class AnalysisIDsForm(forms.Form):

    ids = forms.CharField(
                    widget=forms.Textarea,
                    label='Space separated list of analysis ids')

    def clean(self):
        data = self.cleaned_data
        ids = data.get('ids')

        if not ids or ids.isspace():
            raise forms.ValidationError('No analysis_ids found')

        id_pattern = re.compile(settings.ID_PATTERN)

        cleaned_ids = []

        for i in ids.split():
            id = i.strip()
            if not id:
                continue
            if id_pattern.match(id) and id not in cleaned_ids:
                cleaned_ids.append(id)

        data['ids'] = cleaned_ids

        return data

cghub/apps/cart/views.py
import logging

from urllib2 import URLError

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import transaction
from django.db.utils import DatabaseError
from django.utils import simplejson as json
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.views.generic.base import TemplateView, View

from cghub.apps.core import browser_text_search
from cghub.apps.core.forms import AnalysisIDsForm
from cghub.apps.core.requests import (
        RequestMinimal, RequestDetailJSON, get_results_for_ids)
from cghub.apps.core.utils import (
        get_filters_dict, paginator_params, add_message,
        remove_message)

from .forms import SelectedItemsForm, AllItemsForm
from .utils import (
        Cart, manifest_xml_generator, metadata_xml_generator,
        summary_tsv_generator, urls_tsv_generator)


cart_logger = logging.getLogger('cart')


def cart_add_selected_files(request):
    form = SelectedItemsForm(request.POST)
    if form.is_valid():
        try:
            message_id = add_message(
                        request, 'info',
                        settings.ADDING_TO_CART_IN_PROGRESS_NOTIFICATION)
            try:
                with transaction.commit_on_success():
                    cart = Cart(request.session)
                    for result in form.cleaned_data['selected_items']:
                        cart.add(result)
                    cart.update_stats()
                remove_message(request=request, message_id=message_id)
            except DatabaseError:
                remove_message(request=request, message_id=message_id)
                return {
                    'action': 'message',
                    'title': settings.DATABASE_ERROR_NOTIFICATION_TITLE,
                    'content': settings.DATABASE_ERROR_NOTIFICATION}
            return {'action': 'redirect', 'redirect': reverse('cart_page')}
        except Exception as e:
            cart_logger.error('Error while adding to cart: %s' % unicode(e))
    else:
        cart_logger.error('SelectedItemsForm not valid: %s' % unicode(form.errors))


def cart_add_all_files(request):
    # 'Add all to cart' pressed
    form = AllItemsForm(request.POST)
    if form.is_valid():
        try:
            # calculate query
            raw_filters = form.cleaned_data['filters']
            filters = get_filters_dict(raw_filters)
            q = raw_filters.get('q')
            queries = []
            if q:
                # FIXME: temporary hack to work around GNOS not quoting Solr query
                # FIXME: this is temporary hack, need for multiple requests will be fixed at CGHub
                if browser_text_search.useAllMetadataIndex:
                    query = {'all_metadata': browser_text_search.ws_query(q)}
                    query.update(filters)
                    queries = [query]
                else:
                    query = {'xml_text': u"(%s)" % q}
                    query.update(filters)
                    queries = [query, {'analysis_id': q}]
            if not queries:
                queries = [filters]

            message_id = add_message(
                        request, 'info',
                        settings.ADDING_TO_CART_IN_PROGRESS_NOTIFICATION)
            try:
                with transaction.commit_on_success():
                    cart = Cart(request.session)
                    for query in queries:
                        api_request = RequestMinimal(query=query)
                        for result in api_request.call():
                            cart.add(result)
                        cart.update_stats()
                remove_message(request, message_id)
            except DatabaseError:
                remove_message(request, message_id)
                return {
                    'action': 'message',
                    'title': settings.DATABASE_ERROR_NOTIFICATION_TITLE,
                    'content': settings.DATABASE_ERROR_NOTIFICATION}
            return {'action': 'redirect', 'redirect': reverse('cart_page')}
        except Exception as e:
            cart_logger.error('Error while adding all files to cart: %s' % unicode(e))
    else:
        cart_logger.error('AllItemsForm not valid: %s' % unicode(form.errors))


def cart_add_files(request):
    if not request.is_ajax():
        raise Http404
    filters = request.POST.get('filters')
    if filters:
        result = cart_add_all_files(request)
    else:
        result = cart_add_selected_files(request)
    result = result or {'action': 'error'}
    return HttpResponse(json.dumps(result), mimetype="application/json")


class CartView(TemplateView):
    """
    Lists files in cart
    """
    template_name = 'cart/cart.html'

    def get_context_data(self, **kwargs):
        cart = Cart(self.request.session)
        sort_by = self.request.GET.get('sort_by')
        offset, limit = paginator_params(self.request)
        # will be saved to cookie in get method
        self.paginator_limit = limit
        return {
            'results': cart.page(offset=offset, limit=limit, sort_by=sort_by),
            'num_results': cart.all_count,
            'size': cart.size}

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        response = self.render_to_response(context)
        if request.GET and response.status_code == 200:
            response.set_cookie(settings.PAGINATOR_LIMIT_COOKIE,
                    self.paginator_limit,
                    max_age=settings.COOKIE_MAX_AGE,
                    path=reverse('home_page'))
        return response


class CartAddRemoveItemsView(View):
    """
    Handles files added to cart
    """

    http_method_names = ['post']

    def post(self, request, action):
        if 'add' == action:
            return cart_add_files(request)
        if 'remove' == action:
            form = AnalysisIDsForm(request.POST or None)
            if form.is_valid():
                try:
                    with transaction.commit_on_success():
                        cart = Cart(request.session)
                        for analysis_id in form.cleaned_data['ids']:
                            cart.remove(analysis_id)
                        cart.update_stats()
                except DatabaseError:
                    add_message(
                            request, 'error',
                            settings.DATABASE_ERROR_NOTIFICATION,
                            once=True)
        return HttpResponseRedirect(reverse('cart_page'))


class CartAddItem(View):

    http_method_names = ['post']

    def post(self, request, analysis_id):
        api_request = RequestDetailJSON(query={'analysis_id': analysis_id})
        try:
            result = api_request.call().next()
        except StopIteration:
            raise URLError('No results for analysis_id == %s' % analysis_id)
        try:
            with transaction.commit_on_success():
                cart = Cart(request.session)
                cart.add(result)
                cart.update_stats()
        except DatabaseError:
            add_message(
                    request, 'error',
                    settings.DATABASE_ERROR_NOTIFICATION,
                    once=True)
        return HttpResponseRedirect(reverse('cart_page'))


class CartClearView(View):
    """
    Handels clearing cart
    """
    def post(self, request):
        try:
            with transaction.commit_on_success():
                cart = Cart(request.session)
                cart.clear()
        except DatabaseError:
            add_message(
                    request, 'error', 
                    settings.DATABASE_ERROR_NOTIFICATION, once=True)
        return HttpResponseRedirect(reverse('cart_page'))


def manifest(request):
    if request.GET.get('gzip'):
        response = HttpResponse(
                manifest_xml_generator(request, compress=True),
                content_type='application/x-gzip')
        response['Content-Disposition'] = 'attachment; filename=manifest.xml.gz'
    else:
        response = HttpResponse(
                manifest_xml_generator(request),
                content_type='text/xml')
        response['Content-Disposition'] = 'attachment; filename=manifest.xml'
    return response


def data_urls(request):
    if request.GET.get('gzip'):
        response = HttpResponse(
                urls_tsv_generator(request, compress=True),
                content_type='application/x-gzip')
        response['Content-Disposition'] = 'attachment; filename=urls.txt.gz'
    else:
        response = HttpResponse(
                urls_tsv_generator(request),
                content_type='text/tsv')
        response['Content-Disposition'] = 'attachment; filename=urls.txt'
    return response


def metadata(request):
    if request.GET.get('gzip'):
        response = HttpResponse(
                metadata_xml_generator(request, compress=True),
                content_type='application/x-gzip')
        response['Content-Disposition'] = 'attachment; filename=metadata.xml.gz'
    else:
        response = HttpResponse(
            metadata_xml_generator(request), content_type='text/xml')
        response['Content-Disposition'] = 'attachment; filename=metadata.xml'
    return response


def summary(request):
    if request.GET.get('gzip'):
        response = HttpResponse(
                summary_tsv_generator(request, compress=True),
                content_type='application/x-gzip')
        response['Content-Disposition'] = 'attachment; filename=summary.tsv.gz'
    else:
        response = HttpResponse(
                summary_tsv_generator(request),
                content_type='text/tsv')
        response['Content-Disposition'] = 'attachment; filename=summary.tsv'
    return response


DOWNLOAD_VIEWS = {
    'manifest': manifest,
    'metadata': metadata,
    'summary': summary,
    'urls': data_urls,
}


class CartDownloadFilesView(View):

cghub/apps/help/views.py
import logging

from django.core.urlresolvers import reverse
from django.views.generic.base import View, TemplateView
from django.http import HttpResponseRedirect, Http404
from django.conf import settings

from cghub.apps.core.views import AjaxView

from .models import HelpText


hints_logger = logging.getLogger('help.hints')


class HelpView(TemplateView):
    # override it in urls as
    # ... HelpView.as_view(template_name='help/navbar.html') ...
    template_name = 'help/help.html'

    def dispatch(self, request, *args, **kwargs):
        if request.GET:
            return HttpResponseRedirect(reverse('help_page'))
        return super(HelpView, self).dispatch(request, *args, **kwargs)


class HelpHintView(AjaxView):

    def get_context_data(self, key):
        text = settings.HELP_HINTS.get(key)
        if text:
            return {'success': True, 'text': text}
        else:
            hints_logger.info('%s key is missing' % key)
            return {'success': False}

    def get(self, request, *args, **kwargs):
        if not request.is_ajax():
            raise Http404
        key = request.GET.get('key')
        context = self.get_context_data(key)
        return self.render_to_response(context)


class HelpTextView(AjaxView):

    def get_context_data(self, slug):
        try:
            help_text = HelpText.objects.get(slug=slug)
        except HelpText.DoesNotExist:
            return {'success': False}
        return {
                'success': True,
                'title': help_text.title,
                'content': help_text.content}

    def get(self, request, *args, **kwargs):
        if not request.is_ajax():
            raise Http404
        slug = request.GET.get('slug')
        context = self.get_context_data(slug)
        return self.render_to_response(context)

cghub/templates/core/batch_search.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block description %}{{ block.super }}{% endblock %}
{% block title %}Batch search - {{ block.super }}{% endblock %}
{% block extra_header_css %}
    {% if debug %}
        <link rel="stylesheet/less" type="text/css" href="{% static 'css/core/batch_search.less' %}" media="all">
    {% else %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/core/batch_search.css' %}?v=11" media="all">
    {% endif %}
{% endblock %}
{% block accessibility_links %}
<ul title="Accessibility links" id="accessibility-links">
    <li>
        <a href="#nav-bar" tabindex="1">
            Skip to Navigation bar
        </a>
    </li>
    {% if found %}
    <li>
        <a href="#batch-search-summary" tabindex="2">
            Skip to results summary
        </a>
    </li>
    {% endif %}
    <li>
        {% if ids %}
        <a href="#id-check-all-checkbox" tabindex="3">
            Skip to results table
        </a>
        {% else %}
        <a href="#id_text" tabindex="3">
            Skip to batch form
        </a>
        {% endif %}
    </li>
</ul>
{% endblock %}

{% block main_content %}
<div class='batch-search-content'>

<div class="page-header">
<h1>Batch search</h1>
</div>

{% if ids %}
    {% include 'core/batch_search_result.html' %}
{% else %}
    {% include 'core/batch_search_form.html' %}
{% endif %}

</div>
{% endblock %}

{% block extra_body_js %}
    {% if debug %}
        <script type="text/javascript" src="{% static 'js/core/batch_search.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/table.js' %}"></script>
    {% else %}
        <script type="text/javascript" src="{% static 'js/core/batch_search.min.js' %}?v=15"></script>
    {% endif %}
{% endblock %}

cghub/templates/core/batch_search_form.html
<form method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {% if form.non_field_errors %}
        <div class="alert alert-error">
            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <label for="id_text">Enter one or more white-space or line separated sample barcodes; or analysis, aliquot, sample, or participant UUIDs:</label>
    {{ form.text }}
    <label for="id_upload">Or select file of identifiers:</label>
    {{ form.upload }}

    <div class="batch-submit">
        <button type="submit" class="btn">Search</button>
        <button type="reset" class="btn">Reset</button>
    </div>
</form>

cghub/templates/core/batch_search_result.html
{% load search_tags %}
{% load pagination_tags %}

{% if found %}
<ul id="batch-search-summary" tabindex="31">
    <li>Submitted ids: {{ submitted }}</li>
        {% for name, count in found.items %}
        <li>Found by {{ name }}: {{ count }}</li>
        {% endfor %}
    {% if unvalidated %}
    <li>
        Identifiers with wrong format ({{ unvalidated|length }}):
        <div class="ids-not-found">{% for id in unvalidated %}{{ id }} {% endfor %}</div>
    </li>
    {% endif %}
</ul>
{% endif %}

<form method="POST" action="{% url batch_search_page %}">
    {% csrf_token %}
    <textarea name="ids" class="js-ids-storage" style="display: none;" tabindex="-1">{{ ids|join:' ' }}</textarea>
    <input type="hidden" name="add_to_cart" value="">

    <div class="btn-toolbar">
        <div class="cart-btn-group">
            <button class="btn ids-remove">Remove selected items</button>
            <button class="btn ids-add-to-cart">Add {{ ids|length }} items to cart</button>
        </div>
    </div>

    {% items_per_page request %}

    <div class="column-select-label">
        <label for="id-columns-selector" class="js-common-tooltip" data-key="columns-menu">
            Columns:
        </label>
    </div>
    <select id="id-columns-selector" class="column-select" title="Select columns to display in results area" multiple>
        <option value="(Toggle all)">(Toggle all)</option>
    </select>

    {% include 'data_table.html' %}

    {% items_per_page request %}

    {% with num_results=ids|length %}
        {% pagination %}
    {% endwith %}

    <div class="btn-toolbar">
        <div class="cart-btn-group">
            <button class="btn ids-remove">Remove selected items</button>
            <button class="btn ids-add-to-cart">Add {{ ids|length }} items to cart</button>
        </div>
    </div>
</form>

cghub/templates/core/details_table.html
{% load search_tags %}

{% if res %}
    {% if is_ajax %}
        {% comment %} This will be shown in popup {% endcomment %}
        {% if in_cart %}
            <a href="{% url item_details analysis_id %}#raw-xml" class="btn">Show metadata XML</a>
            <span>In your cart</span>
        {% else %}
            <a href="{% url item_details analysis_id %}#raw-xml" class="btn js-common-tooltip" data-key="details-show-xml">Show metadata XML</a>
            <button type="submit" class="btn js-cart-add-item-button js-common-tooltip" data-key="details-add-to-cart" data-action="{% url cart_add_item analysis_id %}">Add to cart</button>
        {% endif %}
    {% else %}
        <h2 class="hidden">Details table:</h2>
    {% endif %}
    <table class="table table-bordered js-details-table" summary="details for file with analysis id = {{ analysis_id }}" id="main-content" tabindex="0">
        <caption class="hidden">returned file details</caption>
        {% details_table res %}
    </table>
    {% if not is_ajax %}
        <h2 id="raw-xml">Metadata XML:</h2>
        <form action="{% url metadata analysis_id %}" method="GET">
            {% csrf_token %}
            <input type="hidden" name="last_modified" value="{{ res.last_modified }}">
            <button id="id-download-metadata" class="btn js-common-tooltip" data-key="details-xml-download" tabindex="104">Download XML</button>
        </form>
        {% if in_cart %}
            <span>In your cart</span>
        {% else %}
            <form action="{% url cart_add_item analysis_id %}" method="POST">
                <button type="submit" class="btn js-common-tooltip" data-key="details-add-to-cart">Add to cart</button>
            </form>
        {% endif %}
        <div id="XMLHolder" class="XmlContainer" tabindex="105" title="raw xml"></div>
    {% endif %}
{% else %}
No data.
{% endif %}

cghub/templates/core/item_details.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block description %}{{ block.super }}{% endblock %}
{% block title %}Details for {{ res.analysis_id }} - {{ block.super }}{% endblock %}
{% block extra_header_css %}
    {% if debug %}
        <link rel="stylesheet/less" type="text/css" href="{% static 'css/core/details.less' %}" media="all">
    {% else %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/core/details.css' %}?v=9" media="all">
    {% endif %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/libs/xmldisplay/XMLDisplay.css' %}?v=2" media="all">
{% endblock %}

{% block extra_content %}
    <div class="details-content">
        <div class="page-header">
            <h1>Item details for Analysis Id {{ res.analysis_id }}</h1>
        </div>
        {% include "core/details_table.html" %}
    </div>
{% endblock %}

{% block extra_body_js %}
    {% if debug %}
        <script type="text/javascript" src="{% static 'js/libs/XMLDisplay.js' %}"></script>
    {% else %}
        <script type="text/javascript" src="{% static 'js/libs/XMLDisplay.min.js' %}?v=1"></script>
    {% endif %}
    <script>LoadXMLString('XMLHolder', {{ raw_xml|safe }});</script>
{% endblock %}

cghub/templates/core/messages.html
<div class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.level }}">
        <button type="button" class="close" data-dismiss="alert"{% if message.id %} data-message-url="{% url message_remove message.id %}"{% endif %}>&times;</button>
        {{ message.content|safe }}
    </div>
    {% endfor %}
</div>

cghub/templates/core/search.html
{% extends 'base.html' %}
{% load search_tags %}
{% load pagination_tags %}
{% load static from staticfiles %}
{% block description %}{{ block.super }}{% endblock %}
{% block title %}Browser - {{ block.super }}{% endblock %}
{% block extra_header_css %}
    {% if debug %}
        <link rel="stylesheet/less" type="text/css" href="{% static 'css/core/search.less' %}" media="all">
    {% else %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/core/search.css' %}?v=14" media="all">
    {% endif %}
{% endblock %}
{% block accessibility_links %}
<ul title="Accessibility links" id="accessibility-links">
    <li>
        <a href="#nav-bar" tabindex="1">
            Skip to Navigation bar
        </a>
    </li>
    <li>
        <a href="#filters-bar" tabindex="2">
            Skip to Filters
        </a>
    </li>
    <li>
        <a href="#results-summary" tabindex="3">
            Skip to Summary of results
        </a>
    </li>
    <li>
        <a href="#data-table" tabindex="4">
            Skip to Main results
        </a>
    </li>
</ul>
{% endblock %}
{% block extra_sidebar %}
    {% include 'bam_filter_sidebar.html' %}
{% endblock %}
{% block extra_content %}
    <section class="page-header">
        {% if num_results == None %}
            <h1>
                Search BAM Files
                <small>You can search BAM by different parameters</small>
            </h1>
        {% else %}
            <h1>
                Browse available data<br/>
                <small>Select and add to cart to download data or metadata</small>
            </h1>
        {% endif %}
    </section>
    {% if num_results %}
        <section id="results-summary" aria-labelledby="results-summary" tabindex="52">
            <div>Found <span class="js-num-results">{{ num_results }}</span> results</div>
            <div class="applied-filters">{% applied_filters request %}</div>
        </section>
        {% if search_notification %}
            <div class="alert search-notification">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ search_notification|safe }}
            </div>
        {% endif %}
        <form action="{% url cart_add_remove_items action='add' %}" method="POST" id="id_add_files_form" data-many-files="{{ MANY_FILES }}">
            {% csrf_token %}
            <div class="btn-toolbar">
                <div class="search-btn-group">
                    <button class="btn add-to-cart-btn js-common-tooltip" type="submit" data-key="results-add-to-cart-button">Add to cart</button>
                    <button class="btn add-all-to-cart-btn js-common-tooltip" type="button" data-key="results-add-all-to-cart-button" >Add all to cart</button>
                </div>
            </div>
            {% items_per_page request %}
            <div class="column-select-label">
                <label for="id-columns-selector" class="js-common-tooltip" data-key="columns-menu">
                    Columns:
                </label>
            </div>
            <select id="id-columns-selector" class="column-select" title="Select columns to display in results area" multiple>
                <option value="(Toggle all)">(Toggle all)</option>
            </select>
            {% include 'data_table.html' %}
            {% items_per_page request %}
            {% pagination %}
            <div class="btn-toolbar">
                <div class="search-btn-group">
                    <button class="btn add-to-cart-btn js-common-tooltip" type="submit" data-key="results-add-to-cart-button">Add to cart</button>
                    <button class="btn add-all-to-cart-btn js-common-tooltip" type="button" data-key="results-add-all-to-cart-button">Add all to cart</button>
                </div>
            </div>
        </form>
    {% else %}
        <section id="results-summary" aria-labelledby="results-summary" tabindex="52">
            <div class="applied-filters">{% applied_filters request %}</div>
        </section>
        {% if message %}
            <h4>{{ message }}</h4>
        {% endif %}
    {% endif %}
{% endblock %}
{% block extra_body_js %}
    {% if debug %}
        <script type="text/javascript" src="{% static 'js/core/search.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/table.js' %}"></script>
    {% else %}
        <script type="text/javascript" src="{% static 'js/core/search.min.js' %}?v=31"></script>
    {% endif %}
{% endblock %}